version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    image: levinsonvaleri/speedtest_server:latest
    platform: "linux/amd64"
    ports:
      - "3000:3000"
